# IDE for Javascript/React Development
FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y wget libnotify4 libgconf-2-4 libnss3 \
    libgtk2.0-0 libxss1 libgconf-2-4 libasound2 libxtst6 libcanberra-gtk-dev \
    libgl1-mesa-glx libgl1-mesa-dri libxkbfile1 libsecret-1-0 && rm -rf /var/lib/apt/lists/* && \
    wget https://go.microsoft.com/fwlink/?LinkID=760868 -O vscode.deb && \
    dpkg -i vscode.deb && \
    rm vscode.deb && \ 
    apt autoremove && apt clean

# Uncomment one of these lines to execute visual studio code after built
# CMD code --verbose --disable-gpu
# CMD code --verbose
CMD code

